In [2]:
import pandas as pd

operators = pd.read_csv('/content/1__Operator_Work_Schedule.csv')
skills = pd.read_csv('/content/2__Topic_Interactions_with_Higher_Missing_Rate.csv')
topics = pd.read_csv('/content/3__Hourly_Intensity_by_Category.csv')

operators.set_index('ID', inplace=True)
skills.set_index('ID', inplace=True)
topics.set_index('Category', inplace=True)

In [3]:
operators.head()

0  1  2  3  4  5  6  7  8  9  ...  14  15  16  17  18  19  20  21  22  \
ID                                    ...                                       
751033  0  0  0  0  0  0  0  1  1  1  ...   0   0   0   0   0   0   0   0   0   
462254  0  0  0  0  0  0  0  0  0  1  ...   1   1   0   0   0   0   0   0   0   
307525  0  1  1  1  1  1  1  1  0  0  ...   0   0   0   0   0   0   0   0   0   
302875  0  0  0  0  0  0  0  0  0  0  ...   1   1   1   1   1   1   1   1   0   
941069  0  0  0  0  1  1  1  1  1  1  ...   1   1   0   0   0   0   0   0   0   

        23  
ID          
751033   0  
462254   0  
307525   0  
302875   0  
941069   0  

[5 rows x 24 columns]

In [4]:
skills.head()

1   2   3   4   5   6   7   8   9  10
ID                                           
751033  5   7   7   2  11   3   7   8  12   7
462254  5   1   6   7  12   3   9   6   1   2
307525  4   7   9   1   2  10   1   4  -1  10
302875  2  11   4  12  10  12   7  -1   4   2
941069  9   9  11   4   7   2  11  11  -1   7

In [5]:
topics.head()

0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  \
Category                                          ...                           
1          6  27  40  23   8  17  17  17  21  25  ...  21  35  28  14  48  22   
2         20   6  28  17  44  33   1   3  47  11  ...  33   4   1  34  36  26   
3          8  30   3  39   1  38   1  42  13  25  ...  48  20   2   4  32  33   
4         10  15  30  19  33   1  21  50  27  45  ...   5  45  17  35  20   1   
5          7  21  22  14  22  46  24  13  31  42  ...   2  25  35  31  28  48   

          20  21  22  23  
Category                  
1          1  14  46  21  
2         50  18  44  28  
3          5  50  24  42  
4         48  26  17  39  
5          4  20  46  27  

[5 rows x 24 columns]

In [6]:
np_operators = operators.to_numpy()
np_operators

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [7]:
np_skills = skills.to_numpy()
np_skills

array([[ 5,  7,  7, ...,  8, 12,  7],
       [ 5,  1,  6, ...,  6,  1,  2],
       [ 4,  7,  9, ...,  4, -1, 10],
       ...,
       [ 3,  8,  3, ...,  9, 12,  6],
       [ 5, 10,  9, ...,  6,  5, -1],
       [ 6,  5, 11, ...,  9,  1,  3]])

In [8]:
np_topics = topics.to_numpy()
np_topics

array([[ 6, 27, 40, 23,  8, 17, 17, 17, 21, 25,  4,  8, 16, 11, 21, 35,
        28, 14, 48, 22,  1, 14, 46, 21],
       [20,  6, 28, 17, 44, 33,  1,  3, 47, 11, 18, 30, 28, 20, 33,  4,
         1, 34, 36, 26, 50, 18, 44, 28],
       [ 8, 30,  3, 39,  1, 38,  1, 42, 13, 25, 22, 12, 21, 10, 48, 20,
         2,  4, 32, 33,  5, 50, 24, 42],
       [10, 15, 30, 19, 33,  1, 21, 50, 27, 45, 34, 11, 28,  0,  5, 45,
        17, 35, 20,  1, 48, 26, 17, 39],
       [ 7, 21, 22, 14, 22, 46, 24, 13, 31, 42, 15, 13,  7,  2,  2, 25,
        35, 31, 28, 48,  4, 20, 46, 27],
       [ 4, 13, 31, 35,  3, 37, 17, 45,  5, 40, 19, 15, 39, 28, 41, 12,
        31, 26, 44, 28, 26,  6, 35,  1],
       [16, 34, 28, 15, 10, 39, 27, 33, 33, 44, 44, 29, 16, 34,  2, 13,
        42, 13,  2, 36, 36,  7, 19, 25],
       [21, 50, 40, 21, 14, 10, 49, 30, 39,  0, 41, 15, 20, 24, 50,  4,
         5, 13,  5, 21, 48,  1, 18, 27],
       [23, 49, 30, 39,  9, 14, 10, 44, 17, 40, 32,  9, 30, 38, 29, 19,
        32,  5,  0, 22, 

In [10]:
operators

0  1  2  3  4  5  6  7  8  9  ...  14  15  16  17  18  19  20  21  22  \
ID                                    ...                                       
751033  0  0  0  0  0  0  0  1  1  1  ...   0   0   0   0   0   0   0   0   0   
462254  0  0  0  0  0  0  0  0  0  1  ...   1   1   0   0   0   0   0   0   0   
307525  0  1  1  1  1  1  1  1  0  0  ...   0   0   0   0   0   0   0   0   0   
302875  0  0  0  0  0  0  0  0  0  0  ...   1   1   1   1   1   1   1   1   0   
941069  0  0  0  0  1  1  1  1  1  1  ...   1   1   0   0   0   0   0   0   0   
...    .. .. .. .. .. .. .. .. .. ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..   
405226  0  0  0  0  0  1  1  1  1  1  ...   0   0   0   0   0   0   0   0   0   
370997  0  0  0  1  1  1  1  1  1  1  ...   0   0   0   0   0   0   0   0   0   
788279  0  0  0  0  0  0  0  0  1  1  ...   1   1   1   1   1   0   0   0   0   
839647  0  0  0  0  0  0  0  0  1  1  ...   1   1   1   0   0   0   0   0   0   
272698  0  0  0  0  0  0  0  0  0  0  ...   0   1   1   1   1   1   1   0   0   

        23  
ID          
751033   0  
462254   0  
307525   0  
302875   0  
941069   0  
...     ..  
405226   0  
370997   0  
788279   0  
839647   0  
272698   0  

[120 rows x 24 columns]

In [11]:
import numpy as np
import cvxpy as cp

final = np.zeros((operators.shape[0], 10))

for hour in range(24):
  x = cp.Variable((skills.shape[0], 10), integer=True)
  obj = cp.Minimize(cp.sum(cp.multiply(x, np_skills)) - cp.sum(x) * 10000)

  constraints = [
    (cp.sum(cp.multiply(x, np_skills), axis=1) <= 50),
    (cp.sum(x, axis=0) == topics.iloc[:, hour].sum(axis=0)),
    (x >= 0)]

  for i in range(skills.shape[0]):
    if np_operators[i, hour] == 0:
      constraints.append(x[i] == 0)

  for i in range(skills.shape[0]):
    for j in range(2):
      if np_skills[i, j] == -1:
        constraints.append(x[i, j] == 0)

  pp = cp.Problem(obj, constraints)
  pp.solve()

  if str(x.value) != 'None' and str(x.value) != 'inf':
    final = np.add(np.round(x.value, 0), final)

  print(x.value)

  if str(x.value) != 'None' and str(x.value) != 'inf' and hour <= 22:
    topics.iloc[:, hour + 1] += topics.iloc[:, hour].sum(axis=0) - np.sum(x.value, axis=0)

pd.DataFrame(final)

None
None
None
None
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0. 120.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]


<ipython-input-11-cc4cbfd74f43>:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Category
1     17.0
2     33.0
3     38.0
4      1.0
5     46.0
6     37.0
7     39.0
8     10.0
9     14.0
10    50.0
Name: 5, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  topics.iloc[:, hour + 1] += topics.iloc[:, hour].sum(axis=0) - np.sum(x.value, axis=0)


[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0. 27.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0. 140.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0. 12.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


<ipython-input-11-cc4cbfd74f43>:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Category
1     17.0
2      1.0
3      1.0
4     21.0
5     24.0
6     17.0
7     27.0
8     49.0
9     10.0
10    43.0
Name: 6, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  topics.iloc[:, hour + 1] += topics.iloc[:, hour].sum(axis=0) - np.sum(x.value, axis=0)
<ipython-input-11-cc4cbfd74f43>:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Category
1     17.0
2      3.0
3     42.0
4     50.0
5     13.0
6     45.0
7     33.0
8     30.0
9     44.0
10    35.0
Name: 7, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  topics.iloc[:, hour + 1] += topics.iloc[:, hour].sum(axis=0) - np.sum(x.value, axis=0)
<ipython-input-11-cc4cbfd74f43>:33: FutureWarning: S

[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0. 265.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.  50.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0. 287.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.  50.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0. 276.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.  50.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0. 183.]
 [  0.   0.   0. ...   0.   0.   0.]]


<ipython-input-11-cc4cbfd74f43>:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Category
1      4.0
2     18.0
3     22.0
4     34.0
5     15.0
6     19.0
7     44.0
8     41.0
9     32.0
10    47.0
Name: 10, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  topics.iloc[:, hour + 1] += topics.iloc[:, hour].sum(axis=0) - np.sum(x.value, axis=0)
<ipython-input-11-cc4cbfd74f43>:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Category
1      8.0
2     30.0
3     12.0
4     11.0
5     13.0
6     15.0
7     29.0
8     15.0
9      9.0
10    41.0
Name: 11, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  topics.iloc[:, hour + 1] += topics.iloc[:, hour].sum(axis=0) - np.sum(x.value, axis=0)
<ipython-input-11-cc4cbfd74f43>:33: FutureWarning:

[[  0.   0.   0. ...   0.   0.   0.]
 [  0.  50.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0. 253.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.  50.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0. 188.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.  50.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0. 234.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0. 50.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


<ipython-input-11-cc4cbfd74f43>:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Category
1     21.0
2     33.0
3     48.0
4      5.0
5      2.0
6     41.0
7      2.0
8     50.0
9     29.0
10     3.0
Name: 14, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  topics.iloc[:, hour + 1] += topics.iloc[:, hour].sum(axis=0) - np.sum(x.value, axis=0)
<ipython-input-11-cc4cbfd74f43>:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Category
1     35.0
2      4.0
3     20.0
4     45.0
5     25.0
6     12.0
7     13.0
8      4.0
9     19.0
10    34.0
Name: 15, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  topics.iloc[:, hour + 1] += topics.iloc[:, hour].sum(axis=0) - np.sum(x.value, axis=0)
<ipython-input-11-cc4cbfd74f43>:33: FutureWarning:

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


<ipython-input-11-cc4cbfd74f43>:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Category
1     48.0
2     36.0
3     32.0
4     20.0
5     28.0
6     44.0
7      2.0
8      5.0
9      0.0
10     6.0
Name: 18, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  topics.iloc[:, hour + 1] += topics.iloc[:, hour].sum(axis=0) - np.sum(x.value, axis=0)
<ipython-input-11-cc4cbfd74f43>:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Category
1     22.0
2     26.0
3     33.0
4      1.0
5     48.0
6     28.0
7     36.0
8     21.0
9     22.0
10    32.0
Name: 19, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  topics.iloc[:, hour + 1] += topics.iloc[:, hour].sum(axis=0) - np.sum(x.value, axis=0)
<ipython-input-11-cc4cbfd74f43>:33: FutureWarning:

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


<ipython-input-11-cc4cbfd74f43>:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Category
1     14.0
2     18.0
3     50.0
4     26.0
5     20.0
6      6.0
7      7.0
8      1.0
9     14.0
10    20.0
Name: 21, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  topics.iloc[:, hour + 1] += topics.iloc[:, hour].sum(axis=0) - np.sum(x.value, axis=0)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
None
None


<ipython-input-11-cc4cbfd74f43>:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Category
1     46.0
2     44.0
3     24.0
4     17.0
5     46.0
6     35.0
7     19.0
8     18.0
9     14.0
10    48.0
Name: 22, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  topics.iloc[:, hour + 1] += topics.iloc[:, hour].sum(axis=0) - np.sum(x.value, axis=0)


0      1      2      3      4    5      6       7       8       9
0      0.0    0.0    0.0    0.0    0.0  0.0    0.0     0.0     0.0     0.0
1      0.0  350.0    0.0    0.0    0.0  0.0    0.0     0.0     0.0     0.0
2      0.0    0.0    0.0  215.0   89.0  0.0  106.0     0.0   299.0     0.0
3      0.0    0.0  126.0    0.0    0.0  0.0    0.0  1812.0     0.0     0.0
4      0.0    0.0    0.0    0.0    3.0  0.0    0.0     0.0  1122.0     0.0
..     ...    ...    ...    ...    ...  ...    ...     ...     ...     ...
115    0.0    0.0    0.0    0.0  150.0  0.0    0.0     0.0     0.0     0.0
116  300.0    0.0    0.0    0.0    0.0  0.0    0.0     0.0     0.0     0.0
117    0.0    0.0    0.0    0.0    0.0  0.0    0.0     0.0     0.0     0.0
118    0.0    0.0    0.0    0.0    0.0  0.0    0.0     0.0     0.0  1686.0
119    0.0    0.0    0.0    0.0    0.0  0.0    0.0     0.0     0.0     0.0

[120 rows x 10 columns]

In [16]:
final = pd.DataFrame(final)

In [17]:
real_final = pd.concat([operators.reset_index(), final.reset_index()], axis=1)
real_final

ID  0  1  2  3  4  5  6  7  8  ...      0      1      2      3  \
0    751033  0  0  0  0  0  0  0  1  1  ...    0.0    0.0    0.0    0.0   
1    462254  0  0  0  0  0  0  0  0  0  ...    0.0  350.0    0.0    0.0   
2    307525  0  1  1  1  1  1  1  1  0  ...    0.0    0.0    0.0  215.0   
3    302875  0  0  0  0  0  0  0  0  0  ...    0.0    0.0  126.0    0.0   
4    941069  0  0  0  0  1  1  1  1  1  ...    0.0    0.0    0.0    0.0   
..      ... .. .. .. .. .. .. .. .. ..  ...    ...    ...    ...    ...   
115  405226  0  0  0  0  0  1  1  1  1  ...    0.0    0.0    0.0    0.0   
116  370997  0  0  0  1  1  1  1  1  1  ...  300.0    0.0    0.0    0.0   
117  788279  0  0  0  0  0  0  0  0  1  ...    0.0    0.0    0.0    0.0   
118  839647  0  0  0  0  0  0  0  0  1  ...    0.0    0.0    0.0    0.0   
119  272698  0  0  0  0  0  0  0  0  0  ...    0.0    0.0    0.0    0.0   

         4    5      6       7       8       9  
0      0.0  0.0    0.0     0.0     0.0     0.0  
1      0.0  0.0    0.0     0.0     0.0     0.0  
2     89.0  0.0  106.0     0.0   299.0     0.0  
3      0.0  0.0    0.0  1812.0     0.0     0.0  
4      3.0  0.0    0.0     0.0  1122.0     0.0  
..     ...  ...    ...     ...     ...     ...  
115  150.0  0.0    0.0     0.0     0.0     0.0  
116    0.0  0.0    0.0     0.0     0.0     0.0  
117    0.0  0.0    0.0     0.0     0.0     0.0  
118    0.0  0.0    0.0     0.0     0.0  1686.0  
119    0.0  0.0    0.0     0.0     0.0     0.0  

[120 rows x 36 columns]

In [18]:
df_final = pd.concat([real_final.iloc[:, :1], real_final.iloc[:, -10:]], axis=1)
df_final

ID      0      1      2      3      4    5      6       7       8  \
0    751033    0.0    0.0    0.0    0.0    0.0  0.0    0.0     0.0     0.0   
1    462254    0.0  350.0    0.0    0.0    0.0  0.0    0.0     0.0     0.0   
2    307525    0.0    0.0    0.0  215.0   89.0  0.0  106.0     0.0   299.0   
3    302875    0.0    0.0  126.0    0.0    0.0  0.0    0.0  1812.0     0.0   
4    941069    0.0    0.0    0.0    0.0    3.0  0.0    0.0     0.0  1122.0   
..      ...    ...    ...    ...    ...    ...  ...    ...     ...     ...   
115  405226    0.0    0.0    0.0    0.0  150.0  0.0    0.0     0.0     0.0   
116  370997  300.0    0.0    0.0    0.0    0.0  0.0    0.0     0.0     0.0   
117  788279    0.0    0.0    0.0    0.0    0.0  0.0    0.0     0.0     0.0   
118  839647    0.0    0.0    0.0    0.0    0.0  0.0    0.0     0.0     0.0   
119  272698    0.0    0.0    0.0    0.0    0.0  0.0    0.0     0.0     0.0   

          9  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
115     0.0  
116     0.0  
117     0.0  
118  1686.0  
119     0.0  

[120 rows x 11 columns]

In [33]:
priorities = df_final.set_index('ID')
priorities.iloc[:, -10:] = priorities.iloc[:, -10:].rank(axis=1, ascending=False, na_option='keep')
priorities

0    1    2    3    4    5    6    7    8    9
ID                                                      
751033  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5
462254  6.0  1.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0
307525  7.5  7.5  7.5  2.0  4.0  7.5  3.0  7.5  1.0  7.5
302875  6.5  6.5  2.0  6.5  6.5  6.5  6.5  1.0  6.5  6.5
941069  6.5  6.5  6.5  6.5  2.0  6.5  6.5  6.5  1.0  6.5
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
405226  6.0  6.0  6.0  6.0  1.0  6.0  6.0  6.0  6.0  6.0
370997  1.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0
788279  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5
839647  6.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0  1.0
272698  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5

[120 rows x 10 columns]

In [34]:
for i in range(final.shape[0] - 1):
  for j in range(final.shape[1] - 1):
    if skills.iloc[i, j] == -1:
      priorities.iloc[i, j] = np.nan

priorities

0    1    2    3    4    5    6    7    8    9
ID                                                      
751033  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5
462254  6.0  1.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0
307525  7.5  7.5  7.5  2.0  4.0  7.5  3.0  7.5  NaN  7.5
302875  6.5  6.5  2.0  6.5  6.5  6.5  6.5  NaN  6.5  6.5
941069  6.5  6.5  6.5  6.5  2.0  6.5  6.5  6.5  NaN  6.5
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
405226  6.0  6.0  6.0  6.0  1.0  6.0  6.0  6.0  6.0  6.0
370997  1.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0
788279  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5
839647  6.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0  6.0  1.0
272698  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5  5.5

[120 rows x 10 columns]

In [35]:
tobespent = pd.DataFrame(final.to_numpy() * skills.to_numpy())
tobespent[tobespent>0].sum().sum()

np.float64(19471.0)

In [29]:
topicsbefore = pd.read_csv('/content/Random_Values_with_Ordered_IDs.csv')
topicsbefore.set_index('ID', inplace=True)
topicsbefore.head()

1    2   3   4    5    6    7    8    9  10
ID                                                  
751033  21   38  86  45  102  105   69  118   97  64
462254  12  111  74  94   91   19   46   21  105   3
307525  92   57  99  74   38   13  105   46   87  57
302875   5  106  80   0   64   70   74   95  112  28
941069  44   73  21  62    7   20   28   21   16  32

In [30]:
(topicsbefore.to_numpy() * skills.to_numpy()).sum()

np.int64(464641)